### PR TITLE
planner_cspace: use frame_id of incoming message to set dummy robot pose

### LINKED ISSUE #144: initialpose will not work correctly if the map and odom is not the same coordinate
This issue relates to the dummy_robot.
https://github.com/at-wat/neonavigation/blob/master/planner_cspace/src/dummy_robot.cpp#L56-L61

This callback only works correctly if the header.frame_id of the incoming message is "odom" == "map" (like the demo.launch)
If the coordinates are not same coordinate, user cannot specify the robot pose correctly using Rviz (which Fixed Frame="map"). Because the callback overwrites robot pose by incoming message regardless of the frame_id of the incoming message. This callback should consider the transformation from frame_id of the incoming message to "odom" frame to bet set the robot pose correctly.

I'll send PR soon.

### PR DESCRIPTION
**Pull request by ykoga-kyutech**
Fixes #144 

This PR uses TF from frame_id of incoming message to base_link to estimate initial robot pose(odom to base_link).

### CODE REVIEW

File: planner_cspace/src/dummy_robot.cpp [hunk 1]
```diff
@@ -55,9 +57,24 @@ class DummyRobot
...
+    }
+    catch (tf::TransformException &e)
+    {
+      ROS_WARN("%s", e.what());
+      return;
+    }
+
+    tf::Pose pose;
+    tf::poseMsgToTF(msg->pose.pose, pose);
+    const tf::Transform trans_odom_baselink = trans_msg_odom.inverse() * pose;
```
Comment (at-wat) [inline planner_cspace/src/dummy_robot.cpp]: you can use `tf::TransformListener::transformPose` like https://github.com/at-wat/mcl_3dl/blob/master/src/mcl_3dl.cpp#L455-L463

File: planner_cspace/src/dummy_robot.cpp [hunk 2]
```diff
@@ -55,9 +57,24 @@ class DummyRobot
   }
   void cbInit(const geometry_msgs::PoseWithCovarianceStamped::ConstPtr &msg)
   {
-    x_ = msg->pose.pose.position.x;
-    y_ = msg->pose.pose.position.y;
-    yaw_ = tf::getYaw(msg->pose.pose.orientation);
+    tf::StampedTransform trans_msg_odom;
+    try
+    {
+      tfl_.lookupTransform(msg->header.frame_id, "odom", ros::Time(0), trans_msg_odom);
```
Comment (at-wat) [inline planner_cspace/src/dummy_robot.cpp]: `waitForTransform` should be added since `msg->header.frame_id` to `"odom"` transform is not always static.

**Comment by ykoga-kyutech** [comment]
@at-wat All done. Add transformPose instead of lookupTransform and waitForTransform.
